### PR TITLE
Modify the page layout to match oppia layout

### PR DESCRIPTION
**Pull request by ghost**
- Switch from black to green header and footer
- Fix the side navigation menu as the user scroll through content

### CODE REVIEW

**Comment by seanlip** [comment]
@MAKOSCAFEE -- would you mind doing a review? Instructions are here (see "Doing a code review"):

```
https://github.com/oppia/oppia/wiki/Instructions-for-Reviewers#doing-the-review
```

Thanks!

**Comment by makoscafee** [comment]
Hi @amgowano !,
The initial idea was to make Scroll/Follow Sidebar [like this](https://css-tricks.com/examples/ScrollingSidebar/). But this also looks good. One thing, try to minimize window of your browser you will find sidebar overlap and sits on top of the page content. I was able to reproduce this using chrome in Linux. i think you can use media query to try resolve this. Also since you mention you are fixing issue #21 it could be good in the commit message you mention something like "Fixes #21" this will help close the issue once this branch is merged.
Regards!.

**Comment by seanlip** [comment]
Hi @amgowano!

In addition to what @MAKOSCAFEE mentioned, I noticed that the Oppia header is not aligned with the sidebar menu for both large and small viewports. Could this be fixed? Otherwise it looks pretty messy.

sidebar
sidebar2

Also, if we're not using the footer at all, should we just remove it?

Thanks!

**Comment by ghost** [comment]
Hello guys thanks for the comments. I was under the impression that this page doesnt need to work on small devices since when I tried the existing one on my phone it wasnt mobile friendly. Because of that I designed it only with laptop in mind. I will fix the layout issues.

As for the footer, I felt it was necessary to have it there as a visual indicator that the user has reach the end of the contents on a page. 

—

**Comment by seanlip** [comment]
Ah yes, I definitely think this page ought to work on small devices -- if it doesn't, it would be great to make it do so.

Also, I checked with @amitdeutsch about footers in general and I don't think they need to exist for the purpose you mention, since generally you know you're at the end when the scrollbar stops scrolling. So I suggest just removing it.

Thanks!

**Comment by makoscafee** [comment]
@seanlip I also think the other problem was structure of the page was a bit messy. Hard to debug so it was hard to know which part  caused the break when it happens. I have  restructured the code in this PR #27 and I think it will be nice if @amgowano  can help to make it mobile friendly.

**Comment by makoscafee** [comment]
@seanlip this can be closed too

**Comment by seanlip** [comment]
I'm confused. Should this go into master, or be declined? If the former, there are merge conflicts...

**Comment by makoscafee** [comment]
this should be declined these changes were applied to the merged pull request. Because mainly this was to change from black header to oppia color.

**Comment by seanlip** [comment]
OK, closing. Thanks @MAKOSCAFEE !

**Pull request closed without merging**
