### PR TITLE
Add scroll for overflow

### PR DESCRIPTION
**Pull request by lilithxxx**
Currently the sidebar does not show all the contents. 
This PR adds a scrollbar if overflow of contents occur.

### CODE REVIEW

**Comment by lilithxxx** [comment]
@DubeySandeep PTAL

**Comment by DubeySandeep** [comment]
@lilithxxx, Sorry I wasn't aware of this PR, Thanks for the Ping.  

Code review:
Alphabetize the style attributes of .sidebar_fixed.

UI review:
The scroll barss appaers after you scroll a little bit and the phase of this change (without scroll bar to scroll bar) looks bit  unusual. Can we do seomething for that?

**Review by DubeySandeep — CHANGES_REQUESTED** [review]
@lilithxxx, Sorry I wasn't aware of this PR, Thanks for the Ping and creating Pr for this issue.

Code review:
Alphabetize the  CSS properties of `.sidebar_fixed`.

UI review:
The scroll bar appears after you scroll a little bit and the phase of this change (without scroll bar to scrollbar) looks bit unusual. Can we do something for that?

**Comment by lilithxxx** [comment]
Hi @DubeySandeep what about removing sidebar_fixed? We can make the sidebar static and this layout seems simple and better.

**Comment by lilithxxx** [comment]
Hi @DubeySandeep ping?

**Comment by DubeySandeep** [comment]
Hi @lilithxxx, but this way we will be deleting a UI behaviour of having fixed sidebar always in the left that really helps in reading docs. You can undo removing sidebar_fixed changes and I think we can go with that. Thanks!

**Comment by lilithxxx** [comment]
Hi @DubeySandeep PTAL. Is it okay now?

**Review by DubeySandeep — APPROVED** [review]
LGTM! :)

**Pull request merged**
