### PR TITLE
Migrated all images and  Fixed broken links

### PR DESCRIPTION
**Pull request by makoscafee**

### CODE REVIEW

**Comment by seanlip** [comment]
This looks great. Thanks @MAKOSCAFEE!

Just to check, some of the images seem out of date. Would you be up for taking new screenshots and replacing them, or would you prefer me to do so? The ones I'm referring to are
- export.png
- interactiveWidget.png
- noninteractiveContent.png
- oldgallery.png
- rules.png
- rules1.png
- rules2.png
- splash.png
- splash2.png
- splash3.png
- splash4.png
- stateEditor.png

**Comment by makoscafee** [comment]
For quality picture please DO. my 9'' acer min-laptop won't give a quality picture.
Thanks.

**Comment by seanlip** [comment]
OK, sounds good -- will do. Thanks @MAKOSCAFEE!

**Comment by makoscafee** [comment]
And out of curiousity.Do we still need [Index to Documentation ] link at the home page provided we have the sidebar.I thought this was in the old google site because documentation was in separate page?. And please if you could provide me with the link to Development Status(as seen in the home page) in developer documentation; that will be useful, i could not find it in oppia wiki.
Regards.

**Comment by seanlip** [comment]
Nope, I don't think we need the index -- the sidebar works well. It'd be nice if it were a bit narrower, though, I think.

We've also gotten rid of the development status page since GitHub does much of it automatically, so I think we can remove the link.

**Pull request merged**
